wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.19.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710824313.768471
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 1
      - 3
      - 13
      - 23
      4: 3.10.12
      5: 0.16.2
      6: 4.19.2
      8:
      - 5
      13: linux-x86_64
dataset:
  desc: null
  value: CIFAR10
model:
  desc: null
  value: ResNet18
selection:
  desc: null
  value: Uniform
num_exp:
  desc: null
  value: 1
num_eval:
  desc: null
  value: 10
epochs:
  desc: null
  value: 1
data_path:
  desc: null
  value: /home/yancheng/datasets
gpu:
  desc: null
  value: null
print_freq:
  desc: null
  value: 20
fraction:
  desc: null
  value: 0.2
seed:
  desc: null
  value: 12403
workers:
  desc: null
  value: 10
cross:
  desc: null
  value: null
optimizer:
  desc: null
  value: SGD
lr:
  desc: null
  value: 0.1
min_lr:
  desc: null
  value: 0.0001
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 0.0005
nesterov:
  desc: null
  value: true
scheduler:
  desc: null
  value: CosineAnnealingLR
gamma:
  desc: null
  value: 0.5
step_size:
  desc: null
  value: 50
batch:
  desc: null
  value: 128
train_batch:
  desc: null
  value: null
selection_batch:
  desc: null
  value: null
test_interval:
  desc: null
  value: 1
test_fraction:
  desc: null
  value: 1.0
selection_epochs:
  desc: null
  value: 10
selection_momentum:
  desc: null
  value: 0.9
selection_weight_decay:
  desc: null
  value: 0.0005
selection_optimizer:
  desc: null
  value: SGD
selection_nesterov:
  desc: null
  value: true
selection_lr:
  desc: null
  value: 0.1
selection_test_interval:
  desc: null
  value: 1
selection_test_fraction:
  desc: null
  value: 1.0
balance:
  desc: null
  value: true
submodular:
  desc: null
  value: GraphCut
submodular_greedy:
  desc: null
  value: LazyGreedy
uncertainty:
  desc: null
  value: Entropy
save_path:
  desc: null
  value: ./result
resume:
  desc: null
  value: ''
device:
  desc: null
  value: cuda
